name: Release Please

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

      # Just log when a release is created
      # The actual build and upload will be handled by the release.yml workflow
      # when it detects the published release event
      - name: Release Created
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "🚀 Release created: ${{ steps.release.outputs.tag_name }}"
          echo "📦 The release workflow will automatically build and upload module assets."

