# Seasons & Stars Release Workflow
# Builds and packages the module for FoundryVTT distribution

name: Release Module

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v0.3.1)'
        required: true
        type: string
      release_type:
        description: 'Type of release'
        required: false
        default: 'release'
        type: choice
        options:
          - release
          - prerelease

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for version tag extraction
          ref: ${{ github.event.inputs.tag || github.ref }}

      - name: Display Release Info
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "🚀 Manual release triggered for tag: ${{ github.event.inputs.tag }}"
            echo "📦 Release type: ${{ github.event.inputs.release_type }}"
          else
            echo "🚀 Automatic release triggered by published release"
            echo "📦 Release tag: ${{ github.ref_name }}"
          fi

      - name: Release Seasons & Stars
        uses: rayners/foundry-module-actions/release@v4
        with:
          node-version: '18'
          build-command: 'npm run build'
          working-directory: 'dist'
          module-files: 'module.js module.json templates/ calendars/ styles/ languages/ README.md CHANGELOG.md LICENSE'
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}